### PR TITLE
Oprimizations 

### PR DESCRIPTION
**Pull request by MrLava13**
# Oh boy. 
That is the first thing that needs to be done with this **monstrosity** of changes I present.

### The simple changes
The only parts that I changed in this was more of the backbone math stuff, it says that 1k files had been changed, but that is because I hit the "clear all" button. The other changes had to do with:
- Changing the code style in places to match the rest of the project
- Heavily optimizing, and not testing any of it (I have no way to test it)
- Patched some logical bugs, and probably created a boat load more in the process.

### Known issues
- I was lazy and never finished the memory "scaling"/changing of the filters, so it is just sort of *there* in a half working state.

There are plenty more issues with it all since I somewhat rushed this, so just tell me what they are and I'll push some fixes if needed.

It is ready enough... not really...

### CODE REVIEW

**Comment by MrLava13** [comment]
image
Example issue

**Comment by MrLava13** [comment]
@coelacant1 Could you test this? I am just wondering if this works since I do not have any way to test it.

**Comment by GR3Y-SCALE** [comment]
I may be able to test this. I have some matrix's.
What do you need me to test @MrLava13

**Comment by MrLava13** [comment]
Unfortunately, the LED panels that I own do not function, so I cannot tell what all I have broken with the program since I know that has happened... Unfortunately.

**Comment by MrLava13** [comment]
Not worth the effort.

**Pull request closed without merging**
